(() => {
const puzzle=document.querySelector('[data-message-rebuild]');if(!puzzle)return;
const pile=puzzle.querySelector('[data-message-pile]'),grid=puzzle.querySelector('[data-message-grid]'),card=puzzle.querySelector('[data-message-card]'),triesOutput=puzzle.querySelector('[data-message-tries]'),KEY='loreMessageRebuildV1';
const files=['1j.png','2k.png','3j.png','4k.png','5j.png','6k.png','7j.png','8k.png','9j.png','10k.png','11j.png','12k.png','13j.png','14k.png','15j.png','16k.png','17j.png','18k.png','19j.png','20k.png'];const pieces=files.map((file,i)=>({file,position:i+1,speaker:file.includes('j')?'J':'K'}));let state=load(),drag=null;
function shuffle(){const a=pieces.map(p=>p.position);for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function load(){try{const s=JSON.parse(localStorage.getItem(KEY));if(s)return{slots:s.slots||{},free:s.free||{},flipped:!!(s.flipped||s.opened),tries:Number(s.tries)||0,shuffle:Array.isArray(s.shuffle)&&s.shuffle.length===20?s.shuffle:shuffle()}}catch(_){}return{slots:{},free:{},flipped:false,tries:0,shuffle:shuffle()}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function makePiece(p){const x=document.createElement('img');x.className='message-piece';x.src=`assets/images/lore/message/${p.file}`;x.alt=`Message fragment ${p.position}`;x.draggable=false;x.dataset.piece=p.position;x.addEventListener('pointerdown',start);return x}
function initial(n,i){return{x:50+((((i*37)+n*11)%18)-9),y:50+((((i*53)+n*7)%22)-11)}}
function render(){pile.innerHTML='';grid.innerHTML='';if(triesOutput)triesOutput.textContent=state.tries;const used=new Set(Object.values(state.slots).map(Number));state.shuffle.filter(n=>!used.has(n)).forEach((n,i)=>{const x=makePiece(pieces[n-1]),pos=state.free[n]||initial(n,i);x.style.setProperty('--free-x',`${pos.x}%`);x.style.setProperty('--free-y',`${pos.y}%`);x.style.setProperty('--pile-r',`${((n*17)%15)-7}deg`);x.style.zIndex=i+1;pile.appendChild(x)});pieces.forEach(p=>{const row=document.createElement('div');row.className='message-slot-row';const label=document.createElement('div');label.className='message-slot-label';label.textContent=`${p.speaker}:`;const slot=document.createElement('div');slot.className='message-slot';slot.dataset.slot=p.position;const occ=Number(state.slots[p.position]);if(occ){const x=makePiece(pieces[occ-1]);slot.appendChild(x);if(occ===p.position){slot.classList.add('is-correct');x.removeEventListener('pointerdown',start)}else slot.classList.add('is-wrong')}row.append(label,slot);grid.appendChild(row)});const won=pieces.every(p=>Number(state.slots[p.position])===p.position);pile.hidden=won;card.hidden=!won;card.classList.toggle('is-flipped',won&&state.flipped)}
function start(e){if(e.button!==0&&e.pointerType!=='touch')return;const img=e.currentTarget,n=Number(img.dataset.piece),slot=img.closest('.message-slot');if(slot&&slot.classList.contains('is-correct'))return;e.preventDefault();const r=img.getBoundingClientRect();drag={img,n,from:slot?Number(slot.dataset.slot):null,dx:e.clientX-r.left,dy:e.clientY-r.top,target:null,x:e.clientX,y:e.clientY};img.style.setProperty('--drag-width',`${r.width}px`);document.body.appendChild(img);img.classList.add('is-dragging');move(e);window.addEventListener('pointermove',move,{passive:false});window.addEventListener('pointerup',end,{once:true});window.addEventListener('pointercancel',end,{once:true})}
function move(e){if(!drag)return;e.preventDefault();drag.x=e.clientX;drag.y=e.clientY;drag.img.style.setProperty('--drag-x',`${e.clientX-drag.dx}px`);drag.img.style.setProperty('--drag-y',`${e.clientY-drag.dy}px`);document.querySelectorAll('.message-slot.is-target').forEach(x=>x.classList.remove('is-target'));drag.img.style.visibility='hidden';const under=document.elementFromPoint(e.clientX,e.clientY);drag.img.style.visibility='';const slot=under&&under.closest('.message-slot');drag.target=slot&&!slot.classList.contains('is-correct')?slot:null;if(drag.target)drag.target.classList.add('is-target')}
function end(){if(!drag)return;window.removeEventListener('pointermove',move);document.querySelectorAll('.message-slot.is-target').forEach(x=>x.classList.remove('is-target'));const target=drag.target?Number(drag.target.dataset.slot):null;if(drag.from&&Number(state.slots[drag.from])===drag.n)delete state.slots[drag.from];if(target){state.tries++;const displaced=Number(state.slots[target]);if(displaced&&displaced!==drag.n){delete state.slots[target];state.free[displaced]={x:50,y:50}}state.slots[target]=drag.n;delete state.free[drag.n]}else{const r=pile.getBoundingClientRect(),ir=drag.img.getBoundingClientRect(),cx=drag.x-drag.dx+ir.width/2,cy=drag.y-drag.dy+ir.height/2;state.free[drag.n]={x:((cx-r.left)/r.width)*100,y:((cy-r.top)/r.height)*100}}drag.img.remove();drag=null;save();render()}
card.addEventListener('click',()=>{state.flipped=!state.flipped;save();card.classList.toggle('is-flipped',state.flipped)});render();
})();