(() => {
    const puzzle = document.querySelector('[data-message-rebuild]');
    if (!puzzle) return;
    const pile = puzzle.querySelector('[data-message-pile]');
    const grid = puzzle.querySelector('[data-message-grid]');
    const envelope = puzzle.querySelector('[data-message-envelope]');
    const flap = puzzle.querySelector('[data-envelope-flap]');
    const triesOutput = puzzle.querySelector('[data-message-tries]');
    const STORAGE_KEY = 'loreMessageRebuildV1';
    const files = ['1j.png','2k.png','3j.png','4k.png','5j.png','6k.png','7j.png','8k.png','9j.png','10k.png','11j.png','12k.png','13j.png','14k.png','15j.png','16k.png','17j.png','18k.png','19j.png','20k.png'];
    const pieces = files.map((file,index)=>({file,position:index+1,speaker:file.includes('j')?'J':'K'}));
    let state=loadState(), drag=null;
    function makeShuffle(){const a=pieces.map(p=>p.position);for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
    function loadState(){try{const s=JSON.parse(localStorage.getItem(STORAGE_KEY));if(s)return{slots:s.slots||{},free:s.free||{},opened:!!s.opened,tries:Number(s.tries)||0,shuffle:Array.isArray(s.shuffle)&&s.shuffle.length===20?s.shuffle:makeShuffle()};}catch(_){}return{slots:{},free:{},opened:false,tries:0,shuffle:makeShuffle()};}
    function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}
    function createPiece(p){const img=document.createElement('img');img.className='message-piece';img.src=`assets/images/lore/message/${p.file}`;img.alt=`Message fragment ${p.position}`;img.draggable=false;img.dataset.piece=p.position;img.addEventListener('pointerdown',beginDrag);return img;}
    function defaultPos(position,i){return{x:50+((((i*37)+position*11)%18)-9),y:50+((((i*53)+position*7)%22)-11)};}
    function render(){pile.innerHTML='';grid.innerHTML='';if(triesOutput)triesOutput.textContent=state.tries;const placed=new Set(Object.values(state.slots).map(Number));state.shuffle.filter(n=>!placed.has(n)).forEach((n,i)=>{const img=createPiece(pieces[n-1]),pos=state.free[n]||defaultPos(n,i);img.style.setProperty('--free-x',`${pos.x}%`);img.style.setProperty('--free-y',`${pos.y}%`);img.style.setProperty('--pile-r',`${((n*17)%15)-7}deg`);img.style.zIndex=i+1;pile.appendChild(img);});pieces.forEach(p=>{const row=document.createElement('div');row.className='message-slot-row';const label=document.createElement('div');label.className='message-slot-label';label.textContent=`${p.speaker}:`;const slot=document.createElement('div');slot.className='message-slot';slot.dataset.slot=p.position;const occupant=Number(state.slots[p.position]);if(occupant){const img=createPiece(pieces[occupant-1]);slot.appendChild(img);if(occupant===p.position){slot.classList.add('is-correct');img.removeEventListener('pointerdown',beginDrag);}else slot.classList.add('is-wrong');}row.append(label,slot);grid.appendChild(row);});const complete=pieces.every(p=>Number(state.slots[p.position])===p.position);envelope.hidden=!complete;pile.hidden=complete;envelope.classList.toggle('is-open',complete&&state.opened);}
    function beginDrag(e){if(e.button!==0&&e.pointerType!=='touch')return;const img=e.currentTarget,piecePosition=Number(img.dataset.piece),parentSlot=img.closest('.message-slot');if(parentSlot&&parentSlot.classList.contains('is-correct'))return;e.preventDefault();const r=img.getBoundingClientRect();drag={img,piecePosition,fromSlot:parentSlot?Number(parentSlot.dataset.slot):null,offsetX:e.clientX-r.left,offsetY:e.clientY-r.top,target:null,clientX:e.clientX,clientY:e.clientY};img.style.setProperty('--drag-width',`${r.width}px`);document.body.appendChild(img);img.classList.add('is-dragging');moveDrag(e);window.addEventListener('pointermove',moveDrag,{passive:false});window.addEventListener('pointerup',endDrag,{once:true});window.addEventListener('pointercancel',endDrag,{once:true});}
    function moveDrag(e){if(!drag)return;e.preventDefault();drag.clientX=e.clientX;drag.clientY=e.clientY;drag.img.style.setProperty('--drag-x',`${e.clientX-drag.offsetX}px`);drag.img.style.setProperty('--drag-y',`${e.clientY-drag.offsetY}px`);document.querySelectorAll('.message-slot.is-target').forEach(x=>x.classList.remove('is-target'));drag.img.style.visibility='hidden';const under=document.elementFromPoint(e.clientX,e.clientY);drag.img.style.visibility='';const slot=under&&under.closest('.message-slot');drag.target=slot&&!slot.classList.contains('is-correct')?slot:null;if(drag.target)drag.target.classList.add('is-target');}
    function endDrag(){if(!drag)return;window.removeEventListener('pointermove',moveDrag);document.querySelectorAll('.message-slot.is-target').forEach(x=>x.classList.remove('is-target'));const target=drag.target?Number(drag.target.dataset.slot):null;if(drag.fromSlot&&Number(state.slots[drag.fromSlot])===drag.piecePosition)delete state.slots[drag.fromSlot];if(target){state.tries++;const displaced=Number(state.slots[target]);if(displaced&&displaced!==drag.piecePosition){delete state.slots[target];state.free[displaced]={x:50,y:50};}state.slots[target]=drag.piecePosition;delete state.free[drag.piecePosition];}else{const r=pile.getBoundingClientRect(),ir=drag.img.getBoundingClientRect(),cx=drag.clientX-drag.offsetX+ir.width/2,cy=drag.clientY-drag.offsetY+ir.height/2;state.free[drag.piecePosition]={x:Math.max(5,Math.min(95,((cx-r.left)/r.width)*100)),y:Math.max(5,Math.min(95,((cy-r.top)/r.height)*100))};}drag.img.remove();drag=null;save();render();}
    let flapStartY=null;flap.addEventListener('pointerdown',e=>{if(envelope.classList.contains('is-open'))return;flapStartY=e.clientY;flap.setPointerCapture?.(e.pointerId);});flap.addEventListener('pointerup',e=>{if(flapStartY===null)return;const pulled=Math.abs(e.clientY-flapStartY)>20;flapStartY=null;if(!pulled)return;state.opened=true;save();envelope.classList.add('is-open');});render();
})();