(()=>{if(!document.querySelector('link[data-site-theme]')){const l=document.createElement('link');l.rel='stylesheet';l.href='css/theme.css';l.dataset.siteTheme='';document.head.appendChild(l);}})();
const STORAGE_KEY = "jonathanPuzzleUnlocked";
const rows = document.querySelectorAll(".link-row");
function loadUnlockedSections(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||{};}catch{return {};}}
function saveUnlockedSections(unlockedSections){localStorage.setItem(STORAGE_KEY,JSON.stringify(unlockedSections));}
function clearAllPuzzleProgress(){localStorage.removeItem(STORAGE_KEY);localStorage.removeItem("jonathanScrabbleStateV1");localStorage.removeItem("loreMessageRebuildV1");localStorage.removeItem("lorePetNamesV1");localStorage.removeItem("loreArchitecturePuzzleV1");}
function resetPuzzleProgress(){clearAllPuzzleProgress();window.location.reload();}
window.resetPuzzleProgress=resetPuzzleProgress;
const params=new URLSearchParams(window.location.search);
if(params.get("reset")==="1"){clearAllPuzzleProgress();params.delete("reset");const cleanQuery=params.toString();const cleanUrl=window.location.pathname+(cleanQuery?"?"+cleanQuery:"")+window.location.hash;window.history.replaceState({},"",cleanUrl);}
const unlockedSections=loadUnlockedSections();
rows.forEach((row)=>{const sectionId=row.dataset.section,correctPasscode=row.dataset.passcode,input=row.querySelector(".passcode-input"),verifyButton=row.querySelector(".verify-button"),devUnlockButton=row.querySelector(".dev-unlock-button"),link=row.querySelector(".section-link"),tooltip=row.querySelector(".tooltip");let errorTimer=null;function clearError(){input.classList.remove("invalid");tooltip.classList.remove("visible");}function showError(){if(errorTimer!==null)clearTimeout(errorTimer);input.classList.add("invalid");tooltip.classList.add("visible");errorTimer=window.setTimeout(()=>{clearError();errorTimer=null;},3000);}function unlock({save=true}={}){clearError();link.classList.remove("disabled");link.classList.add("unlocked");link.setAttribute("aria-disabled","false");input.disabled=true;verifyButton.disabled=true;if(devUnlockButton)devUnlockButton.disabled=true;if(save){unlockedSections[sectionId]=true;saveUnlockedSections(unlockedSections);}}function verifyPasscode(){if(input.value===correctPasscode){unlock();return;}showError();}if(unlockedSections[sectionId])unlock({save:false});verifyButton.addEventListener("click",verifyPasscode);if(devUnlockButton)devUnlockButton.addEventListener("click",()=>unlock());input.addEventListener("keydown",(event)=>{if(event.key==="Enter")verifyPasscode();});input.addEventListener("input",clearError);link.addEventListener("click",(event)=>{if(!link.classList.contains("unlocked"))event.preventDefault();});});